### ISSUE TITLE
Sort and filter orders and other resource types by date modified

### ISSUE THREAD

**Issue by claudiosanches** [woocommerce/woocommerce-rest-api#37]
Ref https://github.com/woocommerce/woocommerce/issues/17262

**Comment by claudiosanches** [comment]
Thank you for reporting this issue!

I'm closing the issue as it already has a PR, please continue the discussion over at #30

**Comment by timjen3** [comment]
@claudiosanches It looks like the linked ticket will only add filtering for Products / Variations. A lot of people are asking for filtering of orders in this issue. Is there another PR for filtering of Orders?

**Comment by anthonyabc** [comment]
@claudiosanches  #30 Does NOT address this issue.

**Comment by stayhero** [comment]
@claudiosanches Yes, that does not address this issue. We would need to be able to filter for the modified date.

**Comment by kdekok** [comment]
Other issues DO NOT ADDRESS this one. 
Please re-open issue and add` orderby=date_modified`, how hard can that be?

**Comment by kepeder** [comment]
Added another pull-request for querying orders as well by created and modified. https://github.com/woocommerce/woocommerce-rest-api/pull/66

**Comment by codermrrob** [comment]
The lack of this feature makes integration with accounting systems incredibly difficult. Yes it is possible to create some kind of extension/plugin to deal with this but the reason we are trying to use the API is because plugins seem to be somewhat unreliable

**Comment by weaselmetal** [comment]
@claudiosanches if you merged both PR 66 and PR 30, then orders, products and product variants would support the requested filter, correct? You mentioned in the PR that the filter needs to be supported on all objects? Which ones? All that are documented in the API docs? Why would that be the case? What speaks against adding the filter option to objects where people actively requested their addition?

**Comment by MioPedersen** [comment]
Why this has not become a feature years ago is baffling to me. Would you just communicate if this is a feature that will be implemented or not? We have a ton of users who really need this feature, and we're constantly bombarded by issues because of this.

**Comment by homes2001** [comment]
This issue should get reopened. It was closed on Oct 4, 2019 because there was an open PR, but the PR was closed by @kepeder , without anything actually getting merged. The issue described here still remains, we are still looking for a way to only list orders modified after a certain date.

**Comment by Arohonka** [comment]
Would this help, I just found this snippet and it works: https://rudrastyh.com/wordpress/date-range-filter.html

**Comment by kepeder** [comment]
I merged multiple PRs into one, so that one is still open :-)

**Comment by lcs-prbnc** [comment]
I landed here, coming from an issue posted in 2017.
Can't believe the feature is not implemented yet :-1:

**Comment by lucidjay** [comment]
Cannot believe that such a basic feature that has been continuously requested by the community over the past 3 year and it is STILL not implemented...

**Comment by claudiosanches** [comment]
We are considering this feature and it will get introduced in the next version of the REST API.

**Comment by androidcode33** [comment]
This worked for me. With Woo 4.0.x / API v3.

[add_filter('woocommerce_rest_orders_prepare_object_query', function(array $args, \WP_REST_Request $request) {
    $modified_after = $request->get_param('modified_after');

    if (!$modified_after) {
        return $args;
    }

    $args['date_query'][0]['column'] = 'post_modified';
    $args['date_query'][0]['after']  = $modified_after;

    return $args;

}, 10, 2);](url)

[/wp-json/wc/v3/orders/?modified_after=2020-05-09T14:00:00](url)

**Comment by reason8910** [comment]
@androidcode33 Would this function be able to filter products by date_modified?
What changes would have to be made. Thanks

**Comment by androidcode33** [comment]
@reason8910 No need to do any other changes. 

Let me know if it works for you or any other inquiries.

thanks

**Comment by reason8910** [comment]
> @reason8910 No need to do any other changes.
> 
> Let me know if it works for you or any other inquiries.
> 
> thanks

Wouldn't I need to change this line: woocommerce_rest_orders_prepare_object_query to woocommerce_rest_products_prepare_object_query

**Comment by reason8910** [comment]
@androidcode33 
Ive tried woocommerce_rest_orders_prepare_object_query with query: https://yds.com.au/wp-json/wc/v3/products?modified_after=2020-09-09T14:00:00 but it does not filter.

**Comment by androidcode33** [comment]
@reason8910 this worked for me on orders. I haven't tested it with products.

**Comment by weaselmetal** [comment]
@claudiosanches awesome news that this will be taken care of! Could you please point readers of this conversation to the issue(s) that implement the requested features? I found this https://github.com/woocommerce/woocommerce-rest-api/pull/226 but it only deals with ordering, filtering resources by modified date is not part of the change afaict. Thank you!

**Comment by agastiazoro** [comment]
> > @reason8910 No need to do any other changes.
> > Let me know if it works for you or any other inquiries.
> > thanks
> 
> Wouldn't I need to change this line: woocommerce_rest_orders_prepare_object_query to woocommerce_rest_products_prepare_object_query

I've founded it, it's "woocommerce_rest_product_object_query"
